nats.url=${NATS_URL:nats://localhost:4222}

minio.endpoint=${MINIO_ENDPOINT: http://minio-primary-srv:9000}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET: redstore-events}


archiver.batch-size = 100
archiver.flush-interval-seconds = 60