# ===============================
# 1. DATABASE CONFIGURATION
# ===============================
# These match the Env Vars in your identity-depl.yaml
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. JPA / HIBERNATE CONFIGURATION
# ===============================
# Automatically creates/updates tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# 3. JWT & SECURITY
# ===============================
# Pulls from your identity-secrets
app.jwt.secret=${JWT_KEY}

# ===============================
# 4. HEALTH & MONITORING
# ===============================
# Required for the K8s Readiness Probe we added
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# ===============================
#  5. REDIS SENTINEL CONFIGURATION
# ===============================
# Reads the env variables from your identity-depl.yaml
spring.data.redis.sentinel.master=mymaster
spring.data.redis.sentinel.nodes=${REDIS_HOST}:${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}