apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: redstore-platform
build:
  local:
    push: false # Keeps builds local to your Docker Desktop/Minikube
  artifacts:
    - image: zeroop/redstore-client
      context: redstore-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # Syncs your Angular source files directly to the container
          - src: "src/**/*.{ts,html,scss}"
            dest: .
    - image: zeroop/redstore-identity-service
      context: .
      docker:
        dockerfile: services/identity-service/Dockerfile
    - image: zeroop/redstore-archive-service
      context: .
      docker:
        dockerfile: services/archive-service/Dockerfile
    - image: zeroop/redstore-product-service
      context: .
      docker:
        dockerfile: services/product-service/Dockerfile
    - image: zeroop/redstore-inventory-service
      context: .
      docker:
        dockerfile: services/inventory-service/Dockerfile
    - image: zeroop/redstore-snapshot-service
      context: services/snapshot-service
      docker:
        dockerfile: services/snapshot-service/Dockerfile
manifests:
  rawYaml:
#    - infra/k8s/databases/
#    - infra/k8s/secreates/app-secreates.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/identity-depl.yaml
    - infra/k8s/archiver-depl.yaml
    - infra/k8s/product-depl.yaml
    # - infra/k8s/redis/inventory-redis-depl.yaml
    - infra/k8s/inventory-depl.yaml
    - infra/k8s/snapshot-depl.yaml
    - infra/k8s-dev/ingress-srv.yaml