spring.application.name=analytics-service
server.port=${SERVER_PORT:8080}

nats.url=${NATS_URL:nats://nats-srv:4222}

jwt.key=${JWT_KEY:change-me}

analytics.clickhouse.endpoint=${CLICKHOUSE_ENDPOINT:http://clickhouse-srv:8123}
analytics.clickhouse.database=${CLICKHOUSE_DATABASE:analytics}
analytics.clickhouse.username=${CLICKHOUSE_USER:default}
analytics.clickhouse.password=${CLICKHOUSE_PASSWORD:}
