apiVersion: v1
kind: Secret
metadata:
  name: identity-secrets
type: Opaque
stringData:
  JWT_KEY: redstore-secret-key-2026-zeroop-hmac
  REDIS_PASSWORD: YourSecurePassword
  NATS_URL: nats://nats-srv:4222
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-db-creds
type: Opaque
stringData:
  username: identity_admin
  password: identity_password_123