server {
    listen 3000;
    
    root /usr/share/nginx/html;
    index index.html;

    # Handle standard fallbacks for Single Page Applications (SPA)
    location / {
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
    }

    # Explicitly force JavaScript MIME type to avoid blocked loading
    location ~ \.m?js$ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
        default_type application/javascript;
        add_header Content-Type application/javascript;
    }
}