apiVersion: v1
kind: Service
metadata:
  name: deal-srv
spec:
  selector:
    app: deal
  ports:
    - name: deal
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deal-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deal
  template:
    metadata:
      labels:
        app: deal
    spec:
      containers:
        - name: deal
          image: zeroop/redstore-deal-service
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: deal-secrets
                  key: JWT_KEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://deal-db-cluster-rw:5432/deal_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: deal-db-creds
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deal-db-creds
                  key: password
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: deal-secrets
                  key: NATS_URL
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=20"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
