apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: zeroop/redstore-inventory-service
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: JWT_KEY
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://inventory-db-cluster-rw:5432/inventory_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: inventory-db-creds
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-creds
                  key: password
            - name: REDIS_HOST
              value: inventory-redis-srv
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-redis-secrets
                  key: password
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: NATS_URL
            - name: PRODUCT_SERVICE_BASE_URL
              value: http://product-srv:8080
            - name: INVENTORY_INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: inventory-secrets
                  key: INVENTORY_INTERNAL_API_KEY
          ports:
            - containerPort: 8080
